### PR TITLE
Feature/login page

### PR DESCRIPTION
**Pull request by andrewoconnell89**
I reorganized the Angular project a bit and added in the url-router.  If you go to /login it will take you to the login page.

This is hollow until we setup user models but I wanted to work through each major page.

### CODE REVIEW

**Comment by redemma71** [comment]
hey, @andrewoconnell89. 

this looks good, though it isn't previewing for me. webpack compiles fine, but i'm seeing some errors in the console.

also, when i did an "npm install" to load the new dependencies you added, i saw this:

<ccover|project-angular-src>npm install
project-angular-src@0.0.0 /Users/ccover/Documents/my_documents/BU/CS673/project/project-angular-src
├── @angular/animations@5.2.5
├── @angular/cdk@5.2.1
├── UNMET PEER DEPENDENCY @angular/core@5.2.2
├── @angular/material@5.2.1
└── hammerjs@2.0.8

npm WARN @angular/animations@5.2.5 requires a peer of @angular/core@5.2.5 but none was installed.

I revised the package.json file & ran "npm install" a few more times until I got no error messages. 
I pushed my changes to a branch called features/login-page-cdcFeedback. all you really need to do is diff your package.json & the one on this branch. i think you had core set to 5.2.0, and animation set to 5.2.5, so there was a dependency issue on my end.

even so, i am not seeing anything when I browse to "http://localhost:4200". what does your page look like?

a little more work, but it seems like this is close. you put a heck of a lot of work into this. great work!

chad

**Comment by redemma71** [comment]
@andrewoconnell89.

here is a screencap of my browser & the error messages:

screen shot 2018-02-19 at 1 00 51 pm

**Comment by redemma71** [comment]
@andrewoconnell89 

this might be promising: https://github.com/webpack/webpack-dev-server/issues/416

**Comment by andrewoconnell89** [comment]
wow i just learned a ton about node package requirements.  I ended up downgrading angular down from 5.2.5 to 5.2.2 and typescript to 2.6.2  in addition i added ajv to the express project.

After making those changes I was able to npm install both projects with no warning/errors

I also cleaned up the routes in the angular project so it will default route to login.  Sorry i didn't clarify to go to /login

**Pull request merged**
