### PR TITLE
Features/155276163

### PR DESCRIPTION
**Pull request by redemma71**
Hello, @kanishqbagri, @andrewoconnell89, @CodeDNA & @GitLoverBen. 

This branch includes updates to the data models (both the models themselves & the file name); a new Database Class Diagram; a set of integration tests (though along the "happy path" so we will want to add some other tests); and updated route names.

Please pull the branch, build locally & run the server ("npm start" from inside of /project folder.)  I have shared a set of REST calls that you can open in Postman to test add, view one, view all, and delete calls.

Thanks,
Chad

### CODE REVIEW

**Comment by andrewoconnell89** [comment]
Hey Chad,
So i think since i pushed my branch to master we have a branch conflict when trying to merge this branch.  I was able to fix the solution by deleting the old app.get('/' with what you had in this branch.  

This is the part that I'm not sure what the next step is.  I committed this branch on my computer after resolving the branch conflicts.  Do I now push my commits to your branch?


After fixing the branch conflict I was able to run the branch and view projects from mongo.  I am having some trouble adding a project though

What should I put for the default comment when adding a project?

my current postman post is the following

```
POST /add HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: b7dfb105-8764-493e-8cf7-21dd6370c544

{
	"projectName": "a",
	"projectDescription": "b", 
	"repositoryLink": "", 
	"owner": "", 
	"techStack": "", 
	"projectDemo": "", 
	"comments": [{"title":"comment_title", "body":"test_body"} ], 
	"labels": ""
}
```

The error is:
{
    "success": false,
    "message": "Failed to create a new list. Error: ValidationError: comments: Cast to Array failed for value \"[ { title: 'comment_title', body: 'abc' },\n  { title: 'comment_title', body: 'abc' } ]\" at path \"comments\""
}

If i comment out     comments: request.body.comments, in the addProject function everything works fine.

**Comment by redemma71** [comment]
Comments aren’t implemented yet. It is optional anyway. If you can add without the comment, it’s a success.

**Comment by andrewoconnell89** [comment]
I'm getting Validation errors if i leave any of the fields out of the post.  I originally tried doing a push like this:
{
	"projectName": "a",
	"projectDescription": "b", 
}
 but got validation errors.  After some searching on stackoverflow I found that you needed to add each value with an empty string in order to validation to be successful.  I got all of the others to work but I can't get the comments to work because it's of type: [Comments]

Could you send me some post samples you used to test adding data to the database?

**Comment by andrewoconnell89** [comment]
Bump, any updates on this branch?

**Pull request merged**
